name: SEOMAX Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
    apiBase: http://0.0.0.0:11434
  - name: deepseek-r1 7b
    provider: ollama
    model:  deepseek-r1:7b
    apiBase: http://0.0.0.0:11434
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 100000
      maxTokens: 8192
      stream: true
  - name: qwen2.5-coder 7b
    provider: ollama
    model: qwen2.5-coder:7b
    apiBase: http://0.0.0.0:11434
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 32768
      maxTokens: 8192
      stream: true
  - name: qwen3 8b
    provider: ollama
    model: qwen3:8b
    apiBase: http://0.0.0.0:11434
    capabilities:
      - tool_use
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 40960
      maxTokens: 8192
      stream: true
  - name: qwen3 14b
    provider: ollama
    model: qwen3:14b
    apiBase: http://0.0.0.0:11434
    capabilities:
      - tool_use
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 40960
      maxTokens: 8192
      stream: true
    # chatOptions:
    #   baseAgentSystemMessage: |
    #     Follow these steps for each interaction:

    #     1. User Identification:
    #       - You should assume that you are interacting with default_user
    #       - If you have not identified default_user, proactively try to do so.

    #     2. Memory Retrieval:
    #       - Always begin your chat by saying only "Remembering..." and retrieve all relevant information from your knowledge graph
    #       - Always refer to your knowledge graph as your "memory"

    #     3. Memory
    #       - While conversing with the user, be attentive to any new information that falls into these categories:
    #         a) Basic Identity (age, gender, location, job title, education level, etc.)
    #         b) Behaviors (interests, habits, etc.)
    #         c) Preferences (communication style, preferred language, etc.)
    #         d) Goals (goals, targets, aspirations, etc.)
    #         e) Relationships (personal and professional relationships up to 3 degrees of separation)

    #     4. Memory Update:
    #       - If any new information was gathered during the interaction, update your memory as follows:
    #         a) Create entities for recurring organizations, people, and significant events
    #         b) Connect them to the current entities using relations
    #         b) Store facts about them as observations
      
  - name: llama3.1 8b
    provider: ollama
    model: llama3.1:8b
    apiBase: http://0.0.0.0:11434
    capabilities:
      - tool_use
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 131072
      maxTokens: 8192
      stream: true
  - name: qwen2.5-coder 1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://0.0.0.0:11434
    roles:
      - apply
      - autocomplete
    defaultCompletionOptions:
      contextLength: 32768
      maxTokens: 8192
      stream: true
  - name: codellama:latest
    provider: ollama
    model: codellama:latest
    apiBase: http://0.0.0.0:11434
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 16384
      maxTokens: 8192
      stream: true
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
data:
  - name: Local Data Bank
    destination: file:///Users/conor.fehilly/Documents/repos/mcp-examples/.continue/data_stores
    schema: 0.2.0
    level: all