[project]
name = "mcp-web-interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.6",
    "gradio[mcp]>=5.39.0",
    "mcp>=1.10.1",
    "smolagents[litellm,mcp]>=1.20.0",
]
